In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Reading corpus the text file
with open("/content/AI-dataset.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()

In [ ]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [ ]:
word_index_dict = mytokenizer.word_index
word_list = list(word_index_dict.keys())
# mytokenizer.word_index
# word_list

In [ ]:
my_input_sequences = []
for line in mytext.split('\n'):
    #print(line)
    token_list = mytokenizer.texts_to_sequences([line])[0]
    #print(token_list)
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

In [ ]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [ ]:
input_sequences[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,  145, 4790,    1], dtype=int32)

In [ ]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [ ]:
X[1]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,  145, 4790], dtype=int32)

In [ ]:
y

array([4790,    1, 1020, ...,   83,  358, 1673], dtype=int32)

In [ ]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [ ]:
y[1]

array([0., 1., 0., ..., 0., 0., 0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 19, 100)           893200    
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 8932)              1348732   
                                                                 
Total params: 2392532 (9.13 MB)
Trainable params: 2392532 (9.13 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=40, verbose=1)

Epoch 1/40
3176/3176 [==============================] - 41s 12ms/step - loss: 6.2551 - accuracy: 0.0770
Epoch 2/40
3176/3176 [==============================] - 26s 8ms/step - loss: 5.4673 - accuracy: 0.1300
Epoch 3/40
3176/3176 [==============================] - 24s 8ms/step - loss: 5.0557 - accuracy: 0.1553
Epoch 4/40
3176/3176 [==============================] - 24s 7ms/step - loss: 4.7141 - accuracy: 0.1746
Epoch 5/40
3176/3176 [==============================] - 24s 8ms/step - loss: 4.4033 - accuracy: 0.1927
Epoch 6/40
3176/3176 [==============================] - 23s 7ms/step - loss: 4.1073 - accuracy: 0.2165
Epoch 7/40
3176/3176 [==============================] - 24s 8ms/step - loss: 3.8254 - accuracy: 0.2427
Epoch 8/40
3176/3176 [==============================] - 24s 8ms/step - loss: 3.5604 - accuracy: 0.2747
Epoch 9/40
3176/3176 [==============================] - 24s 7ms/step - loss: 3.3121 - accuracy: 0.3111
Epoch 10/40
3176/3176 [==============================] - 23s 7ms/step - 

In [ ]:
input_text = "rutik"
# print(word_list)
predict_next_words=5
for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    # print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 18ms/step
rutik the man who entered was
